# This is a basic workflow that is manually triggered

name: Generate cluster claim workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      clustername:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Cluster name"
        # Default value if no value is explicitly provided
        default: "cluster"
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      numNodes:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Number of nodes in this cluster"
        # Default value if no value is explicitly provided
        default: "1"
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job to generate the cluster claim yaml
  add-cluster-yaml:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout template
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Generate cluster claim
        run: |
          cp demo/template/cluster-claim-template.yaml ./demo/clusters/${{ inputs.clustername }}-cluster.yaml
          sed -i 's/{{cluster-name}}/${{ inputs.clustername }}/g' ./demo/clusters/${{ inputs.clustername }}-cluster.yaml
          sed -i 's/{{num-nodes}}/${{ inputs.numNodes }}/g' ./demo/clusters/${{ inputs.clustername }}-cluster.yaml

      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0

      - name: Check Kyverno install
        run: kyverno version

      - name: Validate cluster claim
        run: |
          kyverno apply ./kyverno/policies/crossplane -b main  --resource=./demo/clusters/${{ inputs.clustername }}-cluster.yaml

      - name: Setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit file
        run: |
          git add ./demo/clusters/${{ inputs.clustername }}-cluster.yaml
          git commit -m "Created cluster claim"
          git push origin
